name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          
          #Languages
          plugin_languages: yes
          plugin_languages_limit: 4
          
          #Habits
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_charts: yes
          config_timezone: America/Santo Domingo
          
          #Calendar
          plugin_calendar: yes
          
          #Achivements
          plugin_achievements: yes
          plugin_achievements_display: compact

          config_order: base.header, languages, habits, achievements
